connect_air(agartala, ahmedabad, 1913).
connect_air(ahmedabad, agartala, 1913).
connect_air(agartala, bangalore, 1883).
connect_air(bangalore, agartala, 1883).
connect_air(agartala, bhubaneshwar, 687).
connect_air(bhubaneshwar, agartala, 687).
connect_air(agartala, bombay, 1978).
connect_air(bombay, agartala, 1978).
connect_air(agartala, calcutta, 330).
connect_air(calcutta, agartala, 330).
connect_air(agartala, chandigarh, 1626).
connect_air(chandigarh, agartala, 1626).
connect_air(agartala, cochin, 2221).
connect_air(cochin, agartala, 2221).
connect_air(agartala, delhi, 1502).
connect_air(delhi, agartala, 1502).
connect_air(agartala, hyderabad, 1514).
connect_air(hyderabad, agartala, 1514).
connect_air(agartala, indore, 1582).
connect_air(indore, agartala, 1582).
connect_air(agartala, jaipur, 1596).
connect_air(jaipur, agartala, 1596).
connect_air(agartala, kanpur, 1142).
connect_air(kanpur, agartala, 1142).
connect_air(agartala, lucknow, 1093).
connect_air(lucknow, agartala, 1093).
connect_air(agartala, madras, 1671).
connect_air(madras, agartala, 1671).
connect_air(agartala, nagpur, 1290).
connect_air(nagpur, agartala, 1290).
connect_air(agartala, nasik, 1856).
connect_air(nasik, agartala, 1856).
connect_air(agartala, panjim, 2050).
connect_air(panjim, agartala, 2050).
connect_air(agartala, patna, 652).
connect_air(patna, agartala, 652).
connect_air(agartala, pondicherry, 1798).
connect_air(pondicherry, agartala, 1798).
connect_air(agartala, pune, 1902).
connect_air(pune, agartala, 1902).
connect_air(agra, ahmedabad, 716).
connect_air(ahmedabad, agra, 716).
connect_air(agra, bangalore, 1582).
connect_air(bangalore, agra, 1582).
connect_air(agra, bhubaneshwar, 1105).
connect_air(bhubaneshwar, agra, 1105).
connect_air(agra, bombay, 1044).
connect_air(bombay, agra, 1044).
connect_air(agra, calcutta, 1164).
connect_air(calcutta, agra, 1164).
connect_air(agra, chandigarh, 414).
connect_air(chandigarh, agra, 414).
connect_air(agra, cochin, 1927).
connect_air(cochin, agra, 1927).
connect_air(agra, delhi, 180).
connect_air(delhi, agra, 180).
connect_air(agra, hyderabad, 1091).
connect_air(hyderabad, agra, 1091).
connect_air(agra, indore, 542).
connect_air(indore, agra, 542).
connect_air(agra, jaipur, 222).
connect_air(jaipur, agra, 222).
connect_air(agra, kanpur, 245).
connect_air(kanpur, agra, 245).
connect_air(agra, lucknow, 294).
connect_air(lucknow, agra, 294).
connect_air(agra, madras, 1589).
connect_air(madras, agra, 1589).
connect_air(agra, nagpur, 680).
connect_air(nagpur, agra, 680).
connect_air(agra, nasik, 908).
connect_air(nasik, agra, 908).
connect_air(agra, panjim, 1371).
connect_air(panjim, agra, 1371).
connect_air(agra, patna, 732).
connect_air(patna, agra, 732).
connect_air(agra, pondicherry, 1708).
connect_air(pondicherry, agra, 1708).
connect_air(agra, pune, 1054).
connect_air(pune, agra, 1054).
connect_air(ahmedabad, bangalore, 1241).
connect_air(bangalore, ahmedabad, 1241).
connect_air(ahmedabad, bhubaneshwar, 1405).
connect_air(bhubaneshwar, ahmedabad, 1405).
connect_air(ahmedabad, bombay, 443).
connect_air(bombay, ahmedabad, 443).
connect_air(ahmedabad, calcutta, 1622).
connect_air(calcutta, ahmedabad, 1622).
connect_air(ahmedabad, chandigarh, 953).
connect_air(chandigarh, ahmedabad, 953).
connect_air(ahmedabad, cochin, 1509).
connect_air(cochin, ahmedabad, 1509).
connect_air(ahmedabad, delhi, 778).
connect_air(delhi, ahmedabad, 778).
connect_air(ahmedabad, hyderabad, 882).
connect_air(hyderabad, ahmedabad, 882).
connect_air(ahmedabad, indore, 340).
connect_air(indore, ahmedabad, 340).
connect_air(ahmedabad, jaipur, 540).
connect_air(jaipur, ahmedabad, 540).
connect_air(ahmedabad, kanpur, 872).
connect_air(kanpur, ahmedabad, 872).
connect_air(ahmedabad, lucknow, 946).
connect_air(lucknow, ahmedabad, 946).
connect_air(ahmedabad, madras, 1376).
connect_air(madras, ahmedabad, 1376).
connect_air(ahmedabad, nagpur, 705).
connect_air(nagpur, ahmedabad, 705).
connect_air(ahmedabad, nasik, 362).
connect_air(nasik, ahmedabad, 362).
connect_air(ahmedabad, panjim, 850).
connect_air(panjim, ahmedabad, 850).
connect_air(ahmedabad, patna, 1307).
connect_air(patna, ahmedabad, 1307).
connect_air(ahmedabad, pondicherry, 1454).
connect_air(pondicherry, ahmedabad, 1454).
connect_air(ahmedabad, pune, 521).
connect_air(pune, ahmedabad, 521).
connect_air(allahabad, ahmedabad, 979).
connect_air(ahmedabad, allahabad, 979).
connect_air(allahabad, bangalore, 1458).
connect_air(bangalore, allahabad, 1458).
connect_air(allahabad, bhubaneshwar, 703).
connect_air(bhubaneshwar, allahabad, 703).
connect_air(allahabad, bombay, 1164).
connect_air(bombay, allahabad, 1164).
connect_air(allahabad, calcutta, 736).
connect_air(calcutta, allahabad, 736).
connect_air(allahabad, chandigarh, 772).
connect_air(chandigarh, allahabad, 772).
connect_air(allahabad, cochin, 1822).
connect_air(cochin, allahabad, 1822).
connect_air(allahabad, delhi, 580).
connect_air(delhi, allahabad, 580).
connect_air(allahabad, hyderabad, 962).
connect_air(hyderabad, allahabad, 962).
connect_air(allahabad, indore, 680).
connect_air(indore, allahabad, 680).
connect_air(allahabad, jaipur, 627).
connect_air(jaipur, allahabad, 627).
connect_air(allahabad, kanpur, 189).
connect_air(kanpur, allahabad, 189).
connect_air(allahabad, lucknow, 181).
connect_air(lucknow, allahabad, 181).
connect_air(allahabad, madras, 1388).
connect_air(madras, allahabad, 1388).
connect_air(allahabad, nagpur, 555).
connect_air(nagpur, allahabad, 555).
connect_air(allahabad, nasik, 1025).
connect_air(nasik, allahabad, 1025).
connect_air(allahabad, panjim, 1387).
connect_air(panjim, allahabad, 1387).
connect_air(allahabad, patna, 332).
connect_air(patna, allahabad, 332).
connect_air(allahabad, pondicherry, 1519).
connect_air(pondicherry, allahabad, 1519).
connect_air(allahabad, pune, 1128).
connect_air(pune, allahabad, 1128).
connect_air(amritsar, ahmedabad, 984).
connect_air(ahmedabad, amritsar, 984).
connect_air(amritsar, bangalore, 2097).
connect_air(bangalore, amritsar, 2097).
connect_air(amritsar, bhubaneshwar, 1670).
connect_air(bhubaneshwar, amritsar, 1670).
connect_air(amritsar, bombay, 1413).
connect_air(bombay, amritsar, 1413).
connect_air(amritsar, calcutta, 1673).
connect_air(calcutta, amritsar, 1673).
connect_air(amritsar, chandigarh, 208).
connect_air(chandigarh, amritsar, 208).
connect_air(amritsar, cochin, 2418).
connect_air(cochin, amritsar, 2418).
connect_air(amritsar, delhi, 403).
connect_air(delhi, amritsar, 403).
connect_air(amritsar, hyderabad, 1628).
connect_air(hyderabad, amritsar, 1628).
connect_air(amritsar, indore, 997).
connect_air(indore, amritsar, 997).
connect_air(amritsar, jaipur, 533).
connect_air(jaipur, amritsar, 533).
connect_air(amritsar, kanpur, 784).
connect_air(kanpur, amritsar, 784).
connect_air(amritsar, lucknow, 795).
connect_air(lucknow, amritsar, 795).
connect_air(amritsar, madras, 2140).
connect_air(madras, amritsar, 2140).
connect_air(amritsar, nagpur, 1241).
connect_air(nagpur, amritsar, 1241).
connect_air(amritsar, nasik, 1300).
connect_air(nasik, amritsar, 1300).
connect_air(amritsar, panjim, 1800).
connect_air(panjim, amritsar, 1800).
connect_air(amritsar, patna, 1206).
connect_air(patna, amritsar, 1206).
connect_air(amritsar, pondicherry, 2251).
connect_air(pondicherry, amritsar, 2251).
connect_air(amritsar, pune, 1464).
connect_air(pune, amritsar, 1464).
connect_air(asansol, ahmedabad, 1474).
connect_air(ahmedabad, asansol, 1474).
connect_air(asansol, bangalore, 1550).
connect_air(bangalore, asansol, 1550).
connect_air(asansol, bhubaneshwar, 396).
connect_air(bhubaneshwar, asansol, 396).
connect_air(asansol, bombay, 1548).
connect_air(bombay, asansol, 1548).
connect_air(asansol, calcutta, 189).
connect_air(calcutta, asansol, 189).
connect_air(asansol, chandigarh, 1277).
connect_air(chandigarh, asansol, 1277).
connect_air(asansol, cochin, 1906).
connect_air(cochin, asansol, 1906).
connect_air(asansol, delhi, 1119).
connect_air(delhi, asansol, 1119).
connect_air(asansol, hyderabad, 1129).
connect_air(hyderabad, asansol, 1129).
connect_air(asansol, indore, 1142).
connect_air(indore, asansol, 1142).
connect_air(asansol, jaipur, 1181).
connect_air(jaipur, asansol, 1181).
connect_air(asansol, kanpur, 737).
connect_air(kanpur, asansol, 737).
connect_air(asansol, lucknow, 701).
connect_air(lucknow, asansol, 701).
connect_air(asansol, madras, 1380).
connect_air(madras, asansol, 1380).
connect_air(asansol, nagpur, 859).
connect_air(nagpur, asansol, 859).
connect_air(asansol, nasik, 1422).
connect_air(nasik, asansol, 1422).
connect_air(asansol, panjim, 1652).
connect_air(panjim, asansol, 1652).
connect_air(asansol, patna, 283).
connect_air(patna, asansol, 283).
connect_air(asansol, pondicherry, 1514).
connect_air(pondicherry, asansol, 1514).
connect_air(asansol, pune, 1478).
connect_air(pune, asansol, 1478).
connect_air(bangalore, ahmedabad, 1241).
connect_air(ahmedabad, bangalore, 1241).
connect_air(bangalore, bhubaneshwar, 1198).
connect_air(bhubaneshwar, bangalore, 1198).
connect_air(bangalore, bombay, 847).
connect_air(bombay, bangalore, 847).
connect_air(bangalore, calcutta, 1563).
connect_air(calcutta, bangalore, 1563).
connect_air(bangalore, chandigarh, 1980).
connect_air(chandigarh, bangalore, 1980).
connect_air(bangalore, cochin, 366).
connect_air(cochin, bangalore, 366).
connect_air(bangalore, delhi, 1745).
connect_air(delhi, bangalore, 1745).
connect_air(bangalore, hyderabad, 501).
connect_air(hyderabad, bangalore, 501).
connect_air(bangalore, indore, 1101).
connect_air(indore, bangalore, 1101).
connect_air(bangalore, jaipur, 1564).
connect_air(jaipur, bangalore, 1564).
connect_air(bangalore, kanpur, 1528).
connect_air(kanpur, bangalore, 1528).
connect_air(bangalore, lucknow, 1584).
connect_air(lucknow, bangalore, 1584).
connect_air(bangalore, madras, 288).
connect_air(madras, bangalore, 288).
connect_air(bangalore, nagpur, 924).
connect_air(nagpur, bangalore, 924).
connect_air(bangalore, nasik, 881).
connect_air(nasik, bangalore, 881).
connect_air(bangalore, panjim, 494).
connect_air(panjim, bangalore, 494).
connect_air(bangalore, patna, 1614).
connect_air(patna, bangalore, 1614).
connect_air(bangalore, pondicherry, 265).
connect_air(pondicherry, bangalore, 265).
connect_air(bangalore, pune, 736).
connect_air(pune, bangalore, 736).
connect_air(baroda, ahmedabad, 103).
connect_air(ahmedabad, baroda, 103).
connect_air(baroda, bangalore, 1140).
connect_air(bangalore, baroda, 1140).
connect_air(baroda, bhubaneshwar, 1330).
connect_air(bhubaneshwar, baroda, 1330).
connect_air(baroda, bombay, 361).
connect_air(bombay, baroda, 361).
connect_air(baroda, calcutta, 1562).
connect_air(calcutta, baroda, 1562).
connect_air(baroda, chandigarh, 1004).
connect_air(chandigarh, baroda, 1004).
connect_air(baroda, cochin, 1414).
connect_air(cochin, baroda, 1414).
connect_air(baroda, delhi, 813).
connect_air(delhi, baroda, 813).
connect_air(baroda, hyderabad, 780).
connect_air(hyderabad, baroda, 780).
connect_air(baroda, indore, 279).
connect_air(indore, baroda, 279).
connect_air(baroda, jaipur, 577).
connect_air(jaipur, baroda, 577).
connect_air(baroda, kanpur, 859).
connect_air(kanpur, baroda, 859).
connect_air(baroda, lucknow, 934).
connect_air(lucknow, baroda, 934).
connect_air(baroda, madras, 1273).
connect_air(madras, baroda, 1273).
connect_air(baroda, nagpur, 625).
connect_air(nagpur, baroda, 625).
connect_air(baroda, nasik, 265).
connect_air(nasik, baroda, 265).
connect_air(baroda, panjim, 762).
connect_air(panjim, baroda, 762).
connect_air(baroda, patna, 1271).
connect_air(patna, baroda, 1271).
connect_air(baroda, pondicherry, 1352).
connect_air(pondicherry, baroda, 1352).
connect_air(baroda, pune, 428).
connect_air(pune, baroda, 428).
connect_air(bhopal, ahmedabad, 497).
connect_air(ahmedabad, bhopal, 497).
connect_air(bhopal, bangalore, 1146).
connect_air(bangalore, bhopal, 1146).
connect_air(bhopal, bhubaneshwar, 930).
connect_air(bhubaneshwar, bhopal, 930).
connect_air(bhopal, bombay, 662).
connect_air(bombay, bhopal, 662).
connect_air(bhopal, calcutta, 1126).
connect_air(calcutta, bhopal, 1126).
connect_air(bhopal, chandigarh, 835).
connect_air(chandigarh, bhopal, 835).
connect_air(bhopal, cochin, 1487).
connect_air(cochin, bhopal, 1487).
connect_air(bhopal, delhi, 599).
connect_air(delhi, bhopal, 599).
connect_air(bhopal, hyderabad, 664).
connect_air(hyderabad, bhopal, 664).
connect_air(bhopal, indore, 170).
connect_air(indore, bhopal, 170).
connect_air(bhopal, jaipur, 438).
connect_air(jaipur, bhopal, 438).
connect_air(bhopal, kanpur, 462).
connect_air(kanpur, bhopal, 462).
connect_air(bhopal, lucknow, 535).
connect_air(lucknow, bhopal, 535).
connect_air(bhopal, madras, 1175).
connect_air(madras, bhopal, 1175).
connect_air(bhopal, nagpur, 292).
connect_air(nagpur, bhopal, 292).
connect_air(bhopal, nasik, 522).
connect_air(nasik, bhopal, 522).
connect_air(bhopal, panjim, 943).
connect_air(panjim, bhopal, 943).
connect_air(bhopal, patna, 826).
connect_air(patna, bhopal, 826).
connect_air(bhopal, pondicherry, 1286).
connect_air(pondicherry, bhopal, 1286).
connect_air(bhopal, pune, 644).
connect_air(pune, bhopal, 644).
connect_air(bhubaneshwar, ahmedabad, 1405).
connect_air(ahmedabad, bhubaneshwar, 1405).
connect_air(bhubaneshwar, bangalore, 1198).
connect_air(bangalore, bhubaneshwar, 1198).
connect_air(bhubaneshwar, bombay, 1364).
connect_air(bombay, bhubaneshwar, 1364).
connect_air(bhubaneshwar, calcutta, 365).
connect_air(calcutta, bhubaneshwar, 365).
connect_air(bhubaneshwar, chandigarh, 1474).
connect_air(chandigarh, bhubaneshwar, 1474).
connect_air(bhubaneshwar, cochin, 1543).
connect_air(cochin, bhubaneshwar, 1543).
connect_air(bhubaneshwar, delhi, 1273).
connect_air(delhi, bhubaneshwar, 1273).
connect_air(bhubaneshwar, hyderabad, 838).
connect_air(hyderabad, bhubaneshwar, 838).
connect_air(bhubaneshwar, indore, 1067).
connect_air(indore, bhubaneshwar, 1067).
connect_air(bhubaneshwar, jaipur, 1261).
connect_air(jaipur, bhubaneshwar, 1261).
connect_air(bhubaneshwar, kanpur, 886).
connect_air(kanpur, bhubaneshwar, 886).
connect_air(bhubaneshwar, lucknow, 883).
connect_air(lucknow, bhubaneshwar, 883).
connect_air(bhubaneshwar, madras, 1001).
connect_air(madras, bhubaneshwar, 1001).
connect_air(bhubaneshwar, nagpur, 708).
connect_air(nagpur, bhubaneshwar, 708).
connect_air(bhubaneshwar, nasik, 1258).
connect_air(nasik, bhubaneshwar, 1258).
connect_air(bhubaneshwar, panjim, 1379).
connect_air(panjim, bhubaneshwar, 1379).
connect_air(bhubaneshwar, patna, 596).
connect_air(patna, bhubaneshwar, 596).
connect_air(bhubaneshwar, pondicherry, 1133).
connect_air(pondicherry, bhubaneshwar, 1133).
connect_air(bhubaneshwar, pune, 1272).
connect_air(pune, bhubaneshwar, 1272).
connect_air(bombay, ahmedabad, 443).
connect_air(ahmedabad, bombay, 443).
connect_air(bombay, bangalore, 847).
connect_air(bangalore, bombay, 847).
connect_air(bombay, bhubaneshwar, 1364).
connect_air(bhubaneshwar, bombay, 1364).
connect_air(bombay, calcutta, 1657).
connect_air(calcutta, bombay, 1657).
connect_air(bombay, chandigarh, 1356).
connect_air(chandigarh, bombay, 1356).
connect_air(bombay, cochin, 1079).
connect_air(cochin, bombay, 1079).
connect_air(bombay, delhi, 1153).
connect_air(delhi, bombay, 1153).
connect_air(bombay, hyderabad, 622).
connect_air(hyderabad, bombay, 622).
connect_air(bombay, indore, 511).
connect_air(indore, bombay, 511).
connect_air(bombay, jaipur, 922).
connect_air(jaipur, bombay, 922).
connect_air(bombay, kanpur, 1122).
connect_air(kanpur, bombay, 1122).
connect_air(bombay, lucknow, 1196).
connect_air(lucknow, bombay, 1196).
connect_air(bombay, madras, 1034).
connect_air(madras, bombay, 1034).
connect_air(bombay, nagpur, 689).
connect_air(nagpur, bombay, 689).
connect_air(bombay, nasik, 140).
connect_air(nasik, bombay, 140).
connect_air(bombay, panjim, 411).
connect_air(panjim, bombay, 411).
connect_air(bombay, patna, 1456).
connect_air(patna, bombay, 1456).
connect_air(bombay, pondicherry, 1087).
connect_air(pondicherry, bombay, 1087).
connect_air(bombay, pune, 120).
connect_air(pune, bombay, 120).
connect_air(calcutta, ahmedabad, 1622).
connect_air(ahmedabad, calcutta, 1622).
connect_air(calcutta, bangalore, 1563).
connect_air(bangalore, calcutta, 1563).
connect_air(calcutta, bhubaneshwar, 365).
connect_air(bhubaneshwar, calcutta, 365).
connect_air(calcutta, bombay, 1657).
connect_air(bombay, calcutta, 1657).
connect_air(calcutta, chandigarh, 1466).
connect_air(chandigarh, calcutta, 1466).
connect_air(calcutta, cochin, 1908).
connect_air(cochin, calcutta, 1908).
connect_air(calcutta, delhi, 1305).
connect_air(delhi, calcutta, 1305).
connect_air(calcutta, hyderabad, 1184).
connect_air(hyderabad, calcutta, 1184).
connect_air(calcutta, indore, 1285).
connect_air(indore, calcutta, 1285).
connect_air(calcutta, jaipur, 1360).
connect_air(jaipur, calcutta, 1360).
connect_air(calcutta, kanpur, 921).
connect_air(kanpur, calcutta, 921).
connect_air(calcutta, lucknow, 888).
connect_air(lucknow, calcutta, 888).
connect_air(calcutta, madras, 1364).
connect_air(madras, calcutta, 1364).
connect_air(calcutta, nagpur, 972).
connect_air(nagpur, calcutta, 972).
connect_air(calcutta, nasik, 1538).
connect_air(nasik, calcutta, 1538).
connect_air(calcutta, panjim, 1720).
connect_air(panjim, calcutta, 1720).
connect_air(calcutta, patna, 471).
connect_air(patna, calcutta, 471).
connect_air(calcutta, pondicherry, 1494).
connect_air(pondicherry, calcutta, 1494).
connect_air(calcutta, pune, 1578).
connect_air(pune, calcutta, 1578).
connect_air(calicut, ahmedabad, 1355).
connect_air(ahmedabad, calicut, 1355).
connect_air(calicut, bangalore, 275).
connect_air(bangalore, calicut, 275).
connect_air(calicut, bhubaneshwar, 1472).
connect_air(bhubaneshwar, calicut, 1472).
connect_air(calicut, bombay, 925).
connect_air(bombay, calicut, 925).
connect_air(calicut, calcutta, 1837).
connect_air(calcutta, calicut, 1837).
connect_air(calicut, chandigarh, 2171).
connect_air(chandigarh, calicut, 2171).
connect_air(calicut, cochin, 154).
connect_air(cochin, calicut, 154).
connect_air(calicut, delhi, 1941).
connect_air(delhi, calicut, 1941).
connect_air(calicut, hyderabad, 742).
connect_air(hyderabad, calicut, 742).
connect_air(calicut, indore, 1276).
connect_air(indore, calicut, 1276).
connect_air(calicut, jaipur, 1743).
connect_air(jaipur, calicut, 1743).
connect_air(calicut, kanpur, 1758).
connect_air(kanpur, calicut, 1758).
connect_air(calicut, lucknow, 1818).
connect_air(lucknow, calicut, 1818).
connect_air(calicut, madras, 526).
connect_air(madras, calicut, 526).
connect_air(calicut, nagpur, 1156).
connect_air(nagpur, calicut, 1156).
connect_air(calicut, nasik, 996).
connect_air(nasik, calicut, 996).
connect_air(calicut, panjim, 517).
connect_air(panjim, calicut, 517).
connect_air(calicut, patna, 1877).
connect_air(patna, calicut, 1877).
connect_air(calicut, pondicherry, 443).
connect_air(pondicherry, calicut, 443).
connect_air(calicut, pune, 835).
connect_air(pune, calicut, 835).
connect_air(chandigarh, ahmedabad, 953).
connect_air(ahmedabad, chandigarh, 953).
connect_air(chandigarh, bangalore, 1980).
connect_air(bangalore, chandigarh, 1980).
connect_air(chandigarh, bhubaneshwar, 1474).
connect_air(bhubaneshwar, chandigarh, 1474).
connect_air(chandigarh, bombay, 1356).
connect_air(bombay, chandigarh, 1356).
connect_air(chandigarh, calcutta, 1466).
connect_air(calcutta, chandigarh, 1466).
connect_air(chandigarh, cochin, 2314).
connect_air(cochin, chandigarh, 2314).
connect_air(chandigarh, delhi, 238).
connect_air(delhi, chandigarh, 238).
connect_air(chandigarh, hyderabad, 1496).
connect_air(hyderabad, chandigarh, 1496).
connect_air(chandigarh, indore, 897).
connect_air(indore, chandigarh, 897).
connect_air(chandigarh, jaipur, 436).
connect_air(jaipur, chandigarh, 436).
connect_air(chandigarh, kanpur, 590).
connect_air(kanpur, chandigarh, 590).
connect_air(chandigarh, lucknow, 594).
connect_air(lucknow, chandigarh, 594).
connect_air(chandigarh, madras, 2000).
connect_air(madras, chandigarh, 2000).
connect_air(chandigarh, nagpur, 1092).
connect_air(nagpur, chandigarh, 1092).
connect_air(chandigarh, nasik, 1233).
connect_air(nasik, chandigarh, 1233).
connect_air(chandigarh, panjim, 1723).
connect_air(panjim, chandigarh, 1723).
connect_air(chandigarh, patna, 999).
connect_air(patna, chandigarh, 999).
connect_air(chandigarh, pondicherry, 2116).
connect_air(pondicherry, chandigarh, 2116).
connect_air(chandigarh, pune, 1392).
connect_air(pune, chandigarh, 1392).
connect_air(cochin, ahmedabad, 1509).
connect_air(ahmedabad, cochin, 1509).
connect_air(cochin, bangalore, 366).
connect_air(bangalore, cochin, 366).
connect_air(cochin, bhubaneshwar, 1543).
connect_air(bhubaneshwar, cochin, 1543).
connect_air(cochin, bombay, 1079).
connect_air(bombay, cochin, 1079).
connect_air(cochin, calcutta, 1908).
connect_air(calcutta, cochin, 1908).
connect_air(cochin, chandigarh, 2314).
connect_air(chandigarh, cochin, 2314).
connect_air(cochin, delhi, 2083).
connect_air(delhi, cochin, 2083).
connect_air(cochin, hyderabad, 862).
connect_air(hyderabad, cochin, 862).
connect_air(cochin, indore, 1422).
connect_air(indore, cochin, 1422).
connect_air(cochin, jaipur, 1889).
connect_air(jaipur, cochin, 1889).
connect_air(cochin, kanpur, 1886).
connect_air(kanpur, cochin, 1886).
connect_air(cochin, lucknow, 1945).
connect_air(lucknow, cochin, 1945).
connect_air(cochin, madras, 556).
connect_air(madras, cochin, 556).
connect_air(cochin, nagpur, 1283).
connect_air(nagpur, cochin, 1283).
connect_air(cochin, nasik, 1149).
connect_air(nasik, cochin, 1149).
connect_air(cochin, panjim, 671).
connect_air(panjim, cochin, 671).
connect_air(cochin, patna, 1980).
connect_air(patna, cochin, 1980).
connect_air(cochin, pondicherry, 444).
connect_air(pondicherry, cochin, 444).
connect_air(cochin, pune, 988).
connect_air(pune, cochin, 988).
connect_air(coimbatore, ahmedabad, 1418).
connect_air(ahmedabad, coimbatore, 1418).
connect_air(coimbatore, bangalore, 229).
connect_air(bangalore, coimbatore, 229).
connect_air(coimbatore, bhubaneshwar, 1403).
connect_air(bhubaneshwar, coimbatore, 1403).
connect_air(coimbatore, bombay, 999).
connect_air(bombay, coimbatore, 999).
connect_air(coimbatore, calcutta, 1769).
connect_air(calcutta, coimbatore, 1769).
connect_air(coimbatore, chandigarh, 2196).
connect_air(chandigarh, coimbatore, 2196).
connect_air(coimbatore, cochin, 141).
connect_air(cochin, coimbatore, 141).
connect_air(coimbatore, delhi, 1962).
connect_air(delhi, coimbatore, 1962).
connect_air(coimbatore, hyderabad, 728).
connect_air(hyderabad, coimbatore, 728).
connect_air(coimbatore, indore, 1308).
connect_air(indore, coimbatore, 1308).
connect_air(coimbatore, jaipur, 1774).
connect_air(jaipur, coimbatore, 1774).
connect_air(coimbatore, kanpur, 1755).
connect_air(kanpur, coimbatore, 1755).
connect_air(coimbatore, lucknow, 1812).
connect_air(lucknow, coimbatore, 1812).
connect_air(coimbatore, madras, 425).
connect_air(madras, coimbatore, 425).
connect_air(coimbatore, nagpur, 1151).
connect_air(nagpur, coimbatore, 1151).
connect_air(coimbatore, nasik, 1056).
connect_air(nasik, coimbatore, 1056).
connect_air(coimbatore, panjim, 603).
connect_air(panjim, coimbatore, 603).
connect_air(coimbatore, patna, 1840).
connect_air(patna, coimbatore, 1840).
connect_air(coimbatore, pondicherry, 325).
connect_air(pondicherry, coimbatore, 325).
connect_air(coimbatore, pune, 900).
connect_air(pune, coimbatore, 900).
connect_air(delhi, ahmedabad, 778).
connect_air(ahmedabad, delhi, 778).
connect_air(delhi, bangalore, 1745).
connect_air(bangalore, delhi, 1745).
connect_air(delhi, bhubaneshwar, 1273).
connect_air(bhubaneshwar, delhi, 1273).
connect_air(delhi, bombay, 1153).
connect_air(bombay, delhi, 1153).
connect_air(delhi, calcutta, 1305).
connect_air(calcutta, delhi, 1305).
connect_air(delhi, chandigarh, 238).
connect_air(chandigarh, delhi, 238).
connect_air(delhi, cochin, 2083).
connect_air(cochin, delhi, 2083).
connect_air(delhi, hyderabad, 1259).
connect_air(hyderabad, delhi, 1259).
connect_air(delhi, indore, 673).
connect_air(indore, delhi, 673).
connect_air(delhi, jaipur, 238).
connect_air(jaipur, delhi, 238).
connect_air(delhi, kanpur, 392).
connect_air(kanpur, delhi, 392).
connect_air(delhi, lucknow, 417).
connect_air(lucknow, delhi, 417).
connect_air(delhi, madras, 1762).
connect_air(madras, delhi, 1762).
connect_air(delhi, nagpur, 855).
connect_air(nagpur, delhi, 855).
connect_air(delhi, nasik, 1023).
connect_air(nasik, delhi, 1023).
connect_air(delhi, panjim, 1504).
connect_air(panjim, delhi, 1504).
connect_air(delhi, patna, 854).
connect_air(patna, delhi, 854).
connect_air(delhi, pondicherry, 1879).
connect_air(pondicherry, delhi, 1879).
connect_air(delhi, pune, 1177).
connect_air(pune, delhi, 1177).
connect_air(gwalior, ahmedabad, 670).
connect_air(ahmedabad, gwalior, 670).
connect_air(gwalior, bangalore, 1476).
connect_air(bangalore, gwalior, 1476).
connect_air(gwalior, bhubaneshwar, 1022).
connect_air(bhubaneshwar, gwalior, 1022).
connect_air(gwalior, bombay, 964).
connect_air(bombay, gwalior, 964).
connect_air(gwalior, calcutta, 1109).
connect_air(calcutta, gwalior, 1109).
connect_air(gwalior, chandigarh, 521).
connect_air(chandigarh, gwalior, 521).
connect_air(gwalior, cochin, 1822).
connect_air(cochin, gwalior, 1822).
connect_air(gwalior, delhi, 285).
connect_air(delhi, gwalior, 285).
connect_air(gwalior, hyderabad, 984).
connect_air(hyderabad, gwalior, 984).
connect_air(gwalior, indore, 455).
connect_air(indore, gwalior, 455).
connect_air(gwalior, jaipur, 251).
connect_air(jaipur, gwalior, 251).
connect_air(gwalior, kanpur, 216).
connect_air(kanpur, gwalior, 216).
connect_air(gwalior, lucknow, 284).
connect_air(lucknow, gwalior, 284).
connect_air(gwalior, madras, 1481).
connect_air(madras, gwalior, 1481).
connect_air(gwalior, nagpur, 572).
connect_air(nagpur, gwalior, 572).
connect_air(gwalior, nasik, 826).
connect_air(nasik, gwalior, 826).
connect_air(gwalior, panjim, 1277).
connect_air(panjim, gwalior, 1277).
connect_air(gwalior, patna, 700).
connect_air(patna, gwalior, 700).
connect_air(gwalior, pondicherry, 1600).
connect_air(pondicherry, gwalior, 1600).
connect_air(gwalior, pune, 966).
connect_air(pune, gwalior, 966).
connect_air(hubli, ahmedabad, 896).
connect_air(ahmedabad, hubli, 896).
connect_air(hubli, bangalore, 377).
connect_air(bangalore, hubli, 377).
connect_air(hubli, bhubaneshwar, 1260).
connect_air(bhubaneshwar, hubli, 1260).
connect_air(hubli, bombay, 477).
connect_air(bombay, hubli, 477).
connect_air(hubli, calcutta, 1607).
connect_air(calcutta, hubli, 1607).
connect_air(hubli, chandigarh, 1720).
connect_air(chandigarh, hubli, 1720).
connect_air(hubli, cochin, 615).
connect_air(cochin, hubli, 615).
connect_air(hubli, delhi, 1493).
connect_air(delhi, hubli, 1493).
connect_air(hubli, hyderabad, 424).
connect_air(hyderabad, hubli, 424).
connect_air(hubli, indore, 823).
connect_air(indore, hubli, 823).
connect_air(hubli, jaipur, 1288).
connect_air(jaipur, hubli, 1288).
connect_air(hubli, kanpur, 1348).
connect_air(kanpur, hubli, 1348).
connect_air(hubli, lucknow, 1414).
connect_air(lucknow, hubli, 1414).
connect_air(hubli, madras, 610).
connect_air(madras, hubli, 610).
connect_air(hubli, nagpur, 768).
connect_air(nagpur, hubli, 768).
connect_air(hubli, nasik, 535).
connect_air(nasik, hubli, 535).
connect_air(hubli, panjim, 140).
connect_air(panjim, hubli, 140).
connect_air(hubli, patna, 1546).
connect_air(patna, hubli, 1546).
connect_air(hubli, pondicherry, 633).
connect_air(pondicherry, hubli, 633).
connect_air(hubli, pune, 376).
connect_air(pune, hubli, 376).
connect_air(hyderabad, ahmedabad, 882).
connect_air(ahmedabad, hyderabad, 882).
connect_air(hyderabad, bangalore, 501).
connect_air(bangalore, hyderabad, 501).
connect_air(hyderabad, bhubaneshwar, 838).
connect_air(bhubaneshwar, hyderabad, 838).
connect_air(hyderabad, bombay, 622).
connect_air(bombay, hyderabad, 622).
connect_air(hyderabad, calcutta, 1184).
connect_air(calcutta, hyderabad, 1184).
connect_air(hyderabad, chandigarh, 1496).
connect_air(chandigarh, hyderabad, 1496).
connect_air(hyderabad, cochin, 862).
connect_air(cochin, hyderabad, 862).
connect_air(hyderabad, delhi, 1259).
connect_air(delhi, hyderabad, 1259).
connect_air(hyderabad, indore, 655).
connect_air(indore, hyderabad, 655).
connect_air(hyderabad, jaipur, 1097).
connect_air(jaipur, hyderabad, 1097).
connect_air(hyderabad, kanpur, 1027).
connect_air(kanpur, hyderabad, 1027).
connect_air(hyderabad, lucknow, 1084).
connect_air(lucknow, hyderabad, 1084).
connect_air(hyderabad, madras, 517).
connect_air(madras, hyderabad, 517).
connect_air(hyderabad, nagpur, 424).
connect_air(nagpur, hyderabad, 424).
connect_air(hyderabad, nasik, 574).
connect_air(nasik, hyderabad, 574).
connect_air(hyderabad, panjim, 540).
connect_air(panjim, hyderabad, 540).
connect_air(hyderabad, patna, 1146).
connect_air(patna, hyderabad, 1146).
connect_air(hyderabad, pondicherry, 623).
connect_air(pondicherry, hyderabad, 623).
connect_air(hyderabad, pune, 506).
connect_air(pune, hyderabad, 506).
connect_air(imphal, ahmedabad, 2183).
connect_air(ahmedabad, imphal, 2183).
connect_air(imphal, bangalore, 2165).
connect_air(bangalore, imphal, 2165).
connect_air(imphal, bhubaneshwar, 974).
connect_air(bhubaneshwar, imphal, 974).
connect_air(imphal, bombay, 2265).
connect_air(bombay, imphal, 2265).
connect_air(imphal, calcutta, 621).
connect_air(calcutta, imphal, 621).
connect_air(imphal, chandigarh, 1813).
connect_air(chandigarh, imphal, 1813).
connect_air(imphal, cochin, 2498).
connect_air(cochin, imphal, 2498).
connect_air(imphal, delhi, 1715).
connect_air(delhi, imphal, 1715).
connect_air(imphal, hyderabad, 1804).
connect_air(hyderabad, imphal, 1804).
connect_air(imphal, indore, 1857).
connect_air(indore, imphal, 1857).
connect_air(imphal, jaipur, 1833).
connect_air(jaipur, imphal, 1833).
connect_air(imphal, kanpur, 1379).
connect_air(kanpur, imphal, 1379).
connect_air(imphal, lucknow, 1322).
connect_air(lucknow, imphal, 1322).
connect_air(imphal, madras, 1945).
connect_air(madras, imphal, 1945).
connect_air(imphal, nagpur, 1576).
connect_air(nagpur, imphal, 1576).
connect_air(imphal, nasik, 2141).
connect_air(nasik, imphal, 2141).
connect_air(imphal, panjim, 2341).
connect_air(panjim, imphal, 2341).
connect_air(imphal, patna, 892).
connect_air(patna, imphal, 892).
connect_air(imphal, pondicherry, 2069).
connect_air(pondicherry, imphal, 2069).
connect_air(imphal, pune, 2191).
connect_air(pune, imphal, 2191).
connect_air(indore, ahmedabad, 340).
connect_air(ahmedabad, indore, 340).
connect_air(indore, bangalore, 1101).
connect_air(bangalore, indore, 1101).
connect_air(indore, bhubaneshwar, 1067).
connect_air(bhubaneshwar, indore, 1067).
connect_air(indore, bombay, 511).
connect_air(bombay, indore, 511).
connect_air(indore, calcutta, 1285).
connect_air(calcutta, indore, 1285).
connect_air(indore, chandigarh, 897).
connect_air(chandigarh, indore, 897).
connect_air(indore, cochin, 1422).
connect_air(cochin, indore, 1422).
connect_air(indore, delhi, 673).
connect_air(delhi, indore, 673).
connect_air(indore, hyderabad, 655).
connect_air(hyderabad, indore, 655).
connect_air(indore, jaipur, 467).
connect_air(jaipur, indore, 467).
connect_air(indore, kanpur, 615).
connect_air(kanpur, indore, 615).
connect_air(indore, lucknow, 690).
connect_air(lucknow, indore, 690).
connect_air(indore, madras, 1172).
connect_air(madras, indore, 1172).
connect_air(indore, nagpur, 377).
connect_air(nagpur, indore, 377).
connect_air(indore, nasik, 371).
connect_air(nasik, indore, 371).
connect_air(indore, panjim, 832).
connect_air(panjim, indore, 832).
connect_air(indore, patna, 996).
connect_air(patna, indore, 996).
connect_air(indore, pondicherry, 1272).
connect_air(pondicherry, indore, 1272).
connect_air(indore, pune, 512).
connect_air(pune, indore, 512).
connect_air(jabalpur, ahmedabad, 756).
connect_air(ahmedabad, jabalpur, 756).
connect_air(jabalpur, bangalore, 1162).
connect_air(bangalore, jabalpur, 1162).
connect_air(jabalpur, bhubaneshwar, 686).
connect_air(bhubaneshwar, jabalpur, 686).
connect_air(jabalpur, bombay, 864).
connect_air(bombay, jabalpur, 864).
connect_air(jabalpur, calcutta, 866).
connect_air(calcutta, jabalpur, 866).
connect_air(jabalpur, chandigarh, 899).
connect_air(chandigarh, jabalpur, 899).
connect_air(jabalpur, cochin, 1523).
connect_air(cochin, jabalpur, 1523).
connect_air(jabalpur, delhi, 667).
connect_air(delhi, jabalpur, 667).
connect_air(jabalpur, hyderabad, 662).
connect_air(hyderabad, jabalpur, 662).
connect_air(jabalpur, indore, 423).
connect_air(indore, jabalpur, 423).
connect_air(jabalpur, jaipur, 592).
connect_air(jaipur, jabalpur, 592).
connect_air(jabalpur, kanpur, 368).
connect_air(kanpur, jabalpur, 368).
connect_air(jabalpur, lucknow, 422).
connect_air(lucknow, jabalpur, 422).
connect_air(jabalpur, madras, 1126).
connect_air(madras, jabalpur, 1126).
connect_air(jabalpur, nagpur, 242).
connect_air(nagpur, jabalpur, 242).
connect_air(jabalpur, nasik, 729).
connect_air(nasik, jabalpur, 729).
connect_air(jabalpur, panjim, 1069).
connect_air(panjim, jabalpur, 1069).
connect_air(jabalpur, patna, 593).
connect_air(patna, jabalpur, 593).
connect_air(jabalpur, pondicherry, 1251).
connect_air(pondicherry, jabalpur, 1251).
connect_air(jabalpur, pune, 818).
connect_air(pune, jabalpur, 818).
connect_air(jaipur, ahmedabad, 540).
connect_air(ahmedabad, jaipur, 540).
connect_air(jaipur, bangalore, 1564).
connect_air(bangalore, jaipur, 1564).
connect_air(jaipur, bhubaneshwar, 1261).
connect_air(bhubaneshwar, jaipur, 1261).
connect_air(jaipur, bombay, 922).
connect_air(bombay, jaipur, 922).
connect_air(jaipur, calcutta, 1360).
connect_air(calcutta, jaipur, 1360).
connect_air(jaipur, chandigarh, 436).
connect_air(chandigarh, jaipur, 436).
connect_air(jaipur, cochin, 1889).
connect_air(cochin, jaipur, 1889).
connect_air(jaipur, delhi, 238).
connect_air(delhi, jaipur, 238).
connect_air(jaipur, hyderabad, 1097).
connect_air(hyderabad, jaipur, 1097).
connect_air(jaipur, indore, 467).
connect_air(indore, jaipur, 467).
connect_air(jaipur, kanpur, 455).
connect_air(kanpur, jaipur, 455).
connect_air(jaipur, lucknow, 512).
connect_air(lucknow, jaipur, 512).
connect_air(jaipur, madras, 1611).
connect_air(madras, jaipur, 1611).
connect_air(jaipur, nagpur, 724).
connect_air(nagpur, jaipur, 724).
connect_air(jaipur, nasik, 797).
connect_air(nasik, jaipur, 797).
connect_air(jaipur, panjim, 1287).
connect_air(panjim, jaipur, 1287).
connect_air(jaipur, patna, 945).
connect_air(patna, jaipur, 945).
connect_air(jaipur, pondicherry, 1720).
connect_air(pondicherry, jaipur, 1720).
connect_air(jaipur, pune, 955).
connect_air(pune, jaipur, 955).
connect_air(jamshedpur, ahmedabad, 1398).
connect_air(ahmedabad, jamshedpur, 1398).
connect_air(jamshedpur, bangalore, 1424).
connect_air(bangalore, jamshedpur, 1424).
connect_air(jamshedpur, bhubaneshwar, 282).
connect_air(bhubaneshwar, jamshedpur, 282).
connect_air(jamshedpur, bombay, 1446).
connect_air(bombay, jamshedpur, 1446).
connect_air(jamshedpur, calcutta, 224).
connect_air(calcutta, jamshedpur, 224).
connect_air(jamshedpur, chandigarh, 1286).
connect_air(chandigarh, jamshedpur, 1286).
connect_air(jamshedpur, cochin, 1780).
connect_air(cochin, jamshedpur, 1780).
connect_air(jamshedpur, delhi, 1110).
connect_air(delhi, jamshedpur, 1110).
connect_air(jamshedpur, hyderabad, 1007).
connect_air(hyderabad, jamshedpur, 1007).
connect_air(jamshedpur, indore, 1062).
connect_air(indore, jamshedpur, 1062).
connect_air(jamshedpur, jaipur, 1147).
connect_air(jaipur, jamshedpur, 1147).
connect_air(jamshedpur, kanpur, 720).
connect_air(kanpur, jamshedpur, 720).
connect_air(jamshedpur, lucknow, 696).
connect_air(lucknow, jamshedpur, 696).
connect_air(jamshedpur, madras, 1255).
connect_air(madras, jamshedpur, 1255).
connect_air(jamshedpur, nagpur, 757).
connect_air(nagpur, jamshedpur, 757).
connect_air(jamshedpur, nasik, 1324).
connect_air(nasik, jamshedpur, 1324).
connect_air(jamshedpur, panjim, 1534).
connect_air(panjim, jamshedpur, 1534).
connect_air(jamshedpur, patna, 331).
connect_air(patna, jamshedpur, 331).
connect_air(jamshedpur, pondicherry, 1389).
connect_air(pondicherry, jamshedpur, 1389).
connect_air(jamshedpur, pune, 1371).
connect_air(pune, jamshedpur, 1371).
connect_air(kanpur, ahmedabad, 872).
connect_air(ahmedabad, kanpur, 872).
connect_air(kanpur, bangalore, 1528).
connect_air(bangalore, kanpur, 1528).
connect_air(kanpur, bhubaneshwar, 886).
connect_air(bhubaneshwar, kanpur, 886).
connect_air(kanpur, bombay, 1122).
connect_air(bombay, kanpur, 1122).
connect_air(kanpur, calcutta, 921).
connect_air(calcutta, kanpur, 921).
connect_air(kanpur, chandigarh, 590).
connect_air(chandigarh, kanpur, 590).
connect_air(kanpur, cochin, 1886).
connect_air(cochin, kanpur, 1886).
connect_air(kanpur, delhi, 392).
connect_air(delhi, kanpur, 392).
connect_air(kanpur, hyderabad, 1027).
connect_air(hyderabad, kanpur, 1027).
connect_air(kanpur, indore, 615).
connect_air(indore, kanpur, 615).
connect_air(kanpur, jaipur, 455).
connect_air(jaipur, kanpur, 455).
connect_air(kanpur, lucknow, 75).
connect_air(lucknow, kanpur, 75).
connect_air(kanpur, madras, 1491).
connect_air(madras, kanpur, 1491).
connect_air(kanpur, nagpur, 604).
connect_air(nagpur, kanpur, 604).
connect_air(kanpur, nasik, 982).
connect_air(nasik, kanpur, 982).
connect_air(kanpur, panjim, 1394).
connect_air(panjim, kanpur, 1394).
connect_air(kanpur, patna, 490).
connect_air(patna, kanpur, 490).
connect_air(kanpur, pondicherry, 1618).
connect_air(pondicherry, kanpur, 1618).
connect_air(kanpur, pune, 1106).
connect_air(pune, kanpur, 1106).
connect_air(kolhapur, ahmedabad, 728).
connect_air(ahmedabad, kolhapur, 728).
connect_air(kolhapur, bangalore, 549).
connect_air(bangalore, kolhapur, 549).
connect_air(kolhapur, bhubaneshwar, 1287).
connect_air(bhubaneshwar, kolhapur, 1287).
connect_air(kolhapur, bombay, 302).
connect_air(bombay, kolhapur, 302).
connect_air(kolhapur, calcutta, 1618).
connect_air(calcutta, kolhapur, 1618).
connect_air(kolhapur, chandigarh, 1585).
connect_air(chandigarh, kolhapur, 1585).
connect_air(kolhapur, cochin, 781).
connect_air(cochin, kolhapur, 781).
connect_air(kolhapur, delhi, 1365).
connect_air(delhi, kolhapur, 1365).
connect_air(kolhapur, hyderabad, 458).
connect_air(hyderabad, kolhapur, 458).
connect_air(kolhapur, indore, 692).
connect_air(indore, kolhapur, 692).
connect_air(kolhapur, jaipur, 1149).
connect_air(jaipur, kolhapur, 1149).
connect_air(kolhapur, kanpur, 1256).
connect_air(kanpur, kolhapur, 1256).
connect_air(kolhapur, lucknow, 1326).
connect_air(lucknow, kolhapur, 1326).
connect_air(kolhapur, madras, 762).
connect_air(madras, kolhapur, 762).
connect_air(kolhapur, nagpur, 711).
connect_air(nagpur, kolhapur, 711).
connect_air(kolhapur, nasik, 371).
connect_air(nasik, kolhapur, 371).
connect_air(kolhapur, panjim, 141).
connect_air(panjim, kolhapur, 141).
connect_air(kolhapur, patna, 1504).
connect_air(patna, kolhapur, 1504).
connect_air(kolhapur, pondicherry, 799).
connect_air(pondicherry, kolhapur, 799).
connect_air(kolhapur, pune, 208).
connect_air(pune, kolhapur, 208).
connect_air(lucknow, ahmedabad, 946).
connect_air(ahmedabad, lucknow, 946).
connect_air(lucknow, bangalore, 1584).
connect_air(bangalore, lucknow, 1584).
connect_air(lucknow, bhubaneshwar, 883).
connect_air(bhubaneshwar, lucknow, 883).
connect_air(lucknow, bombay, 1196).
connect_air(bombay, lucknow, 1196).
connect_air(lucknow, calcutta, 888).
connect_air(calcutta, lucknow, 888).
connect_air(lucknow, chandigarh, 594).
connect_air(chandigarh, lucknow, 594).
connect_air(lucknow, cochin, 1945).
connect_air(cochin, lucknow, 1945).
connect_air(lucknow, delhi, 417).
connect_air(delhi, lucknow, 417).
connect_air(lucknow, hyderabad, 1084).
connect_air(hyderabad, lucknow, 1084).
connect_air(lucknow, indore, 690).
connect_air(indore, lucknow, 690).
connect_air(lucknow, jaipur, 512).
connect_air(jaipur, lucknow, 512).
connect_air(lucknow, kanpur, 75).
connect_air(kanpur, lucknow, 75).
connect_air(lucknow, madras, 1537).
connect_air(madras, lucknow, 1537).
connect_air(lucknow, nagpur, 662).
connect_air(nagpur, lucknow, 662).
connect_air(lucknow, nasik, 1056).
connect_air(nasik, lucknow, 1056).
connect_air(lucknow, panjim, 1463).
connect_air(panjim, lucknow, 1463).
connect_air(lucknow, patna, 441).
connect_air(patna, lucknow, 441).
connect_air(lucknow, pondicherry, 1665).
connect_air(pondicherry, lucknow, 1665).
connect_air(lucknow, pune, 1178).
connect_air(pune, lucknow, 1178).
connect_air(ludhiana, ahmedabad, 934).
connect_air(ahmedabad, ludhiana, 934).
connect_air(ludhiana, bangalore, 2004).
connect_air(bangalore, ludhiana, 2004).
connect_air(ludhiana, bhubaneshwar, 1546).
connect_air(bhubaneshwar, ludhiana, 1546).
connect_air(ludhiana, bombay, 1350).
connect_air(bombay, ludhiana, 1350).
connect_air(ludhiana, calcutta, 1549).
connect_air(calcutta, ludhiana, 1549).
connect_air(ludhiana, chandigarh, 90).
connect_air(chandigarh, ludhiana, 90).
connect_air(ludhiana, cochin, 2333).
connect_air(cochin, ludhiana, 2333).
connect_air(ludhiana, delhi, 285).
connect_air(delhi, ludhiana, 285).
connect_air(ludhiana, hyderabad, 1528).
connect_air(hyderabad, ludhiana, 1528).
connect_air(ludhiana, indore, 911).
connect_air(indore, ludhiana, 911).
connect_air(ludhiana, jaipur, 444).
connect_air(jaipur, ludhiana, 444).
connect_air(ludhiana, kanpur, 661).
connect_air(kanpur, ludhiana, 661).
connect_air(ludhiana, lucknow, 671).
connect_air(lucknow, ludhiana, 671).
connect_air(ludhiana, madras, 2037).
connect_air(madras, ludhiana, 2037).
connect_air(ludhiana, nagpur, 1133).
connect_air(nagpur, ludhiana, 1133).
connect_air(ludhiana, nasik, 1232).
connect_air(nasik, ludhiana, 1232).
connect_air(ludhiana, panjim, 1728).
connect_air(panjim, ludhiana, 1728).
connect_air(ludhiana, patna, 1084).
connect_air(patna, ludhiana, 1084).
connect_air(ludhiana, pondicherry, 2151).
connect_air(pondicherry, ludhiana, 2151).
connect_air(ludhiana, pune, 1393).
connect_air(pune, ludhiana, 1393).
connect_air(madras, ahmedabad, 1376).
connect_air(ahmedabad, madras, 1376).
connect_air(madras, bangalore, 288).
connect_air(bangalore, madras, 288).
connect_air(madras, bhubaneshwar, 1001).
connect_air(bhubaneshwar, madras, 1001).
connect_air(madras, bombay, 1034).
connect_air(bombay, madras, 1034).
connect_air(madras, calcutta, 1364).
connect_air(calcutta, madras, 1364).
connect_air(madras, chandigarh, 2000).
connect_air(chandigarh, madras, 2000).
connect_air(madras, cochin, 556).
connect_air(cochin, madras, 556).
connect_air(madras, delhi, 1762).
connect_air(delhi, madras, 1762).
connect_air(madras, hyderabad, 517).
connect_air(hyderabad, madras, 517).
connect_air(madras, indore, 1172).
connect_air(indore, madras, 1172).
connect_air(madras, jaipur, 1611).
connect_air(jaipur, madras, 1611).
connect_air(madras, kanpur, 1491).
connect_air(kanpur, madras, 1491).
connect_air(madras, lucknow, 1537).
connect_air(lucknow, madras, 1537).
connect_air(madras, nagpur, 909).
connect_air(nagpur, madras, 909).
connect_air(madras, nasik, 1035).
connect_air(nasik, madras, 1035).
connect_air(madras, panjim, 744).
connect_air(panjim, madras, 744).
connect_air(madras, patna, 1489).
connect_air(patna, madras, 1489).
connect_air(madras, pondicherry, 136).
connect_air(pondicherry, madras, 136).
connect_air(madras, pune, 916).
connect_air(pune, madras, 916).
connect_air(madurai, ahmedabad, 1576).
connect_air(ahmedabad, madurai, 1576).
connect_air(madurai, bangalore, 344).
connect_air(bangalore, madurai, 344).
connect_air(madurai, bhubaneshwar, 1420).
connect_air(bhubaneshwar, madurai, 1420).
connect_air(madurai, bombay, 1165).
connect_air(bombay, madurai, 1165).
connect_air(madurai, calcutta, 1782).
connect_air(calcutta, madurai, 1782).
connect_air(madurai, chandigarh, 2321).
connect_air(chandigarh, madurai, 2321).
connect_air(madurai, cochin, 204).
connect_air(cochin, madurai, 204).
connect_air(madurai, delhi, 2086).
connect_air(delhi, madurai, 2086).
connect_air(madurai, hyderabad, 832).
connect_air(hyderabad, madurai, 832).
connect_air(madurai, indore, 1445).
connect_air(indore, madurai, 1445).
connect_air(madurai, jaipur, 1907).
connect_air(jaipur, madurai, 1907).
connect_air(madurai, kanpur, 1855).
connect_air(kanpur, madurai, 1855).
connect_air(madurai, lucknow, 1908).
connect_air(lucknow, madurai, 1908).
connect_air(madurai, madras, 419).
connect_air(madras, madurai, 419).
connect_air(madurai, nagpur, 1254).
connect_air(nagpur, madurai, 1254).
connect_air(madurai, nasik, 1214).
connect_air(nasik, madurai, 1214).
connect_air(madurai, panjim, 776).
connect_air(panjim, madurai, 776).
connect_air(madurai, patna, 1897).
connect_air(patna, madurai, 1897).
connect_air(madurai, pondicherry, 288).
connect_air(pondicherry, madurai, 288).
connect_air(madurai, pune, 1062).
connect_air(pune, madurai, 1062).
connect_air(meerut, ahmedabad, 838).
connect_air(ahmedabad, meerut, 838).
connect_air(meerut, bangalore, 1783).
connect_air(bangalore, meerut, 1783).
connect_air(meerut, bhubaneshwar, 1268).
connect_air(bhubaneshwar, meerut, 1268).
connect_air(meerut, bombay, 1207).
connect_air(bombay, meerut, 1207).
connect_air(meerut, calcutta, 1284).
connect_air(calcutta, meerut, 1284).
connect_air(meerut, chandigarh, 214).
connect_air(chandigarh, meerut, 214).
connect_air(meerut, cochin, 2124).
connect_air(cochin, meerut, 2124).
connect_air(meerut, delhi, 61).
connect_air(delhi, meerut, 61).
connect_air(meerut, hyderabad, 1294).
connect_air(hyderabad, meerut, 1294).
connect_air(meerut, indore, 722).
connect_air(indore, meerut, 722).
connect_air(meerut, jaipur, 298).
connect_air(jaipur, meerut, 298).
connect_air(meerut, kanpur, 383).
connect_air(kanpur, meerut, 383).
connect_air(meerut, lucknow, 398).
connect_air(lucknow, meerut, 398).
connect_air(meerut, madras, 1793).
connect_air(madras, meerut, 1793).
connect_air(meerut, nagpur, 884).
connect_air(nagpur, meerut, 884).
connect_air(meerut, nasik, 1076).
connect_air(nasik, meerut, 1076).
connect_air(meerut, panjim, 1554).
connect_air(panjim, meerut, 1554).
connect_air(meerut, patna, 826).
connect_air(patna, meerut, 826).
connect_air(meerut, pondicherry, 1911).
connect_air(pondicherry, meerut, 1911).
connect_air(meerut, pune, 1229).
connect_air(pune, meerut, 1229).
connect_air(nagpur, ahmedabad, 705).
connect_air(ahmedabad, nagpur, 705).
connect_air(nagpur, bangalore, 924).
connect_air(bangalore, nagpur, 924).
connect_air(nagpur, bhubaneshwar, 708).
connect_air(bhubaneshwar, nagpur, 708).
connect_air(nagpur, bombay, 689).
connect_air(bombay, nagpur, 689).
connect_air(nagpur, calcutta, 972).
connect_air(calcutta, nagpur, 972).
connect_air(nagpur, chandigarh, 1092).
connect_air(chandigarh, nagpur, 1092).
connect_air(nagpur, cochin, 1283).
connect_air(cochin, nagpur, 1283).
connect_air(nagpur, delhi, 855).
connect_air(delhi, nagpur, 855).
connect_air(nagpur, hyderabad, 424).
connect_air(hyderabad, nagpur, 424).
connect_air(nagpur, indore, 377).
connect_air(indore, nagpur, 377).
connect_air(nagpur, jaipur, 724).
connect_air(jaipur, nagpur, 724).
connect_air(nagpur, kanpur, 604).
connect_air(kanpur, nagpur, 604).
connect_air(nagpur, lucknow, 662).
connect_air(lucknow, nagpur, 662).
connect_air(nagpur, madras, 909).
connect_air(madras, nagpur, 909).
connect_air(nagpur, nasik, 567).
connect_air(nasik, nagpur, 567).
connect_air(nagpur, panjim, 840).
connect_air(panjim, nagpur, 840).
connect_air(nagpur, patna, 793).
connect_air(patna, nagpur, 793).
connect_air(nagpur, pondicherry, 1029).
connect_air(pondicherry, nagpur, 1029).
connect_air(nagpur, pune, 621).
connect_air(pune, nagpur, 621).
connect_air(nasik, ahmedabad, 362).
connect_air(ahmedabad, nasik, 362).
connect_air(nasik, bangalore, 881).
connect_air(bangalore, nasik, 881).
connect_air(nasik, bhubaneshwar, 1258).
connect_air(bhubaneshwar, nasik, 1258).
connect_air(nasik, bombay, 140).
connect_air(bombay, nasik, 140).
connect_air(nasik, calcutta, 1538).
connect_air(calcutta, nasik, 1538).
connect_air(nasik, chandigarh, 1233).
connect_air(chandigarh, nasik, 1233).
connect_air(nasik, cochin, 1149).
connect_air(cochin, nasik, 1149).
connect_air(nasik, delhi, 1023).
connect_air(delhi, nasik, 1023).
connect_air(nasik, hyderabad, 574).
connect_air(hyderabad, nasik, 574).
connect_air(nasik, indore, 371).
connect_air(indore, nasik, 371).
connect_air(nasik, jaipur, 797).
connect_air(jaipur, nasik, 797).
connect_air(nasik, kanpur, 982).
connect_air(kanpur, nasik, 982).
connect_air(nasik, lucknow, 1056).
connect_air(lucknow, nasik, 1056).
connect_air(nasik, madras, 1035).
connect_air(madras, nasik, 1035).
connect_air(nasik, nagpur, 567).
connect_air(nagpur, nasik, 567).
connect_air(nasik, panjim, 501).
connect_air(panjim, nasik, 501).
connect_air(nasik, patna, 1321).
connect_air(patna, nasik, 1321).
connect_air(nasik, pondicherry, 1104).
connect_air(pondicherry, nasik, 1104).
connect_air(nasik, pune, 165).
connect_air(pune, nasik, 165).
connect_air(panjim, ahmedabad, 850).
connect_air(ahmedabad, panjim, 850).
connect_air(panjim, bangalore, 494).
connect_air(bangalore, panjim, 494).
connect_air(panjim, bhubaneshwar, 1379).
connect_air(bhubaneshwar, panjim, 1379).
connect_air(panjim, bombay, 411).
connect_air(bombay, panjim, 411).
connect_air(panjim, calcutta, 1720).
connect_air(calcutta, panjim, 1720).
connect_air(panjim, chandigarh, 1723).
connect_air(chandigarh, panjim, 1723).
connect_air(panjim, cochin, 671).
connect_air(cochin, panjim, 671).
connect_air(panjim, delhi, 1504).
connect_air(delhi, panjim, 1504).
connect_air(panjim, hyderabad, 540).
connect_air(hyderabad, panjim, 540).
connect_air(panjim, indore, 832).
connect_air(indore, panjim, 832).
connect_air(panjim, jaipur, 1287).
connect_air(jaipur, panjim, 1287).
connect_air(panjim, kanpur, 1394).
connect_air(kanpur, panjim, 1394).
connect_air(panjim, lucknow, 1463).
connect_air(lucknow, panjim, 1463).
connect_air(panjim, madras, 744).
connect_air(madras, panjim, 744).
connect_air(panjim, nagpur, 840).
connect_air(nagpur, panjim, 840).
connect_air(panjim, nasik, 501).
connect_air(nasik, panjim, 501).
connect_air(panjim, patna, 1629).
connect_air(patna, panjim, 1629).
connect_air(panjim, pondicherry, 757).
connect_air(pondicherry, panjim, 757).
connect_air(panjim, pune, 337).
connect_air(pune, panjim, 337).
connect_air(patna, ahmedabad, 1307).
connect_air(ahmedabad, patna, 1307).
connect_air(patna, bangalore, 1614).
connect_air(bangalore, patna, 1614).
connect_air(patna, bhubaneshwar, 596).
connect_air(bhubaneshwar, patna, 596).
connect_air(patna, bombay, 1456).
connect_air(bombay, patna, 1456).
connect_air(patna, calcutta, 471).
connect_air(calcutta, patna, 471).
connect_air(patna, chandigarh, 999).
connect_air(chandigarh, patna, 999).
connect_air(patna, cochin, 1980).
connect_air(cochin, patna, 1980).
connect_air(patna, delhi, 854).
connect_air(delhi, patna, 854).
connect_air(patna, hyderabad, 1146).
connect_air(hyderabad, patna, 1146).
connect_air(patna, indore, 996).
connect_air(indore, patna, 996).
connect_air(patna, jaipur, 945).
connect_air(jaipur, patna, 945).
connect_air(patna, kanpur, 490).
connect_air(kanpur, patna, 490).
connect_air(patna, lucknow, 441).
connect_air(lucknow, patna, 441).
connect_air(patna, madras, 1489).
connect_air(madras, patna, 1489).
connect_air(patna, nagpur, 793).
connect_air(nagpur, patna, 793).
connect_air(patna, nasik, 1321).
connect_air(nasik, patna, 1321).
connect_air(patna, panjim, 1629).
connect_air(panjim, patna, 1629).
connect_air(patna, pondicherry, 1624).
connect_air(pondicherry, patna, 1624).
connect_air(patna, pune, 1406).
connect_air(pune, patna, 1406).
connect_air(pondicherry, ahmedabad, 1454).
connect_air(ahmedabad, pondicherry, 1454).
connect_air(pondicherry, bangalore, 265).
connect_air(bangalore, pondicherry, 265).
connect_air(pondicherry, bhubaneshwar, 1133).
connect_air(bhubaneshwar, pondicherry, 1133).
connect_air(pondicherry, bombay, 1087).
connect_air(bombay, pondicherry, 1087).
connect_air(pondicherry, calcutta, 1494).
connect_air(calcutta, pondicherry, 1494).
connect_air(pondicherry, chandigarh, 2116).
connect_air(chandigarh, pondicherry, 2116).
connect_air(pondicherry, cochin, 444).
connect_air(cochin, pondicherry, 444).
connect_air(pondicherry, delhi, 1879).
connect_air(delhi, pondicherry, 1879).
connect_air(pondicherry, hyderabad, 623).
connect_air(hyderabad, pondicherry, 623).
connect_air(pondicherry, indore, 1272).
connect_air(indore, pondicherry, 1272).
connect_air(pondicherry, jaipur, 1720).
connect_air(jaipur, pondicherry, 1720).
connect_air(pondicherry, kanpur, 1618).
connect_air(kanpur, pondicherry, 1618).
connect_air(pondicherry, lucknow, 1665).
connect_air(lucknow, pondicherry, 1665).
connect_air(pondicherry, madras, 136).
connect_air(madras, pondicherry, 136).
connect_air(pondicherry, nagpur, 1029).
connect_air(nagpur, pondicherry, 1029).
connect_air(pondicherry, nasik, 1104).
connect_air(nasik, pondicherry, 1104).
connect_air(pondicherry, panjim, 757).
connect_air(panjim, pondicherry, 757).
connect_air(pondicherry, patna, 1624).
connect_air(patna, pondicherry, 1624).
connect_air(pondicherry, pune, 971).
connect_air(pune, pondicherry, 971).
connect_air(pune, ahmedabad, 521).
connect_air(ahmedabad, pune, 521).
connect_air(pune, bangalore, 736).
connect_air(bangalore, pune, 736).
connect_air(pune, bhubaneshwar, 1272).
connect_air(bhubaneshwar, pune, 1272).
connect_air(pune, bombay, 120).
connect_air(bombay, pune, 120).
connect_air(pune, calcutta, 1578).
connect_air(calcutta, pune, 1578).
connect_air(pune, chandigarh, 1392).
connect_air(chandigarh, pune, 1392).
connect_air(pune, cochin, 988).
connect_air(cochin, pune, 988).
connect_air(pune, delhi, 1177).
connect_air(delhi, pune, 1177).
connect_air(pune, hyderabad, 506).
connect_air(hyderabad, pune, 506).
connect_air(pune, indore, 512).
connect_air(indore, pune, 512).
connect_air(pune, jaipur, 955).
connect_air(jaipur, pune, 955).
connect_air(pune, kanpur, 1106).
connect_air(kanpur, pune, 1106).
connect_air(pune, lucknow, 1178).
connect_air(lucknow, pune, 1178).
connect_air(pune, madras, 916).
connect_air(madras, pune, 916).
connect_air(pune, nagpur, 621).
connect_air(nagpur, pune, 621).
connect_air(pune, nasik, 165).
connect_air(nasik, pune, 165).
connect_air(pune, panjim, 337).
connect_air(panjim, pune, 337).
connect_air(pune, patna, 1406).
connect_air(patna, pune, 1406).
connect_air(pune, pondicherry, 971).
connect_air(pondicherry, pune, 971).
connect_air(ranchi, ahmedabad, 1304).
connect_air(ahmedabad, ranchi, 1304).
connect_air(ranchi, bangalore, 1413).
connect_air(bangalore, ranchi, 1413).
connect_air(ranchi, bhubaneshwar, 344).
connect_air(bhubaneshwar, ranchi, 344).
connect_air(ranchi, bombay, 1375).
connect_air(bombay, ranchi, 1375).
connect_air(ranchi, calcutta, 325).
connect_air(calcutta, ranchi, 325).
connect_air(ranchi, chandigarh, 1179).
connect_air(chandigarh, ranchi, 1179).
connect_air(ranchi, cochin, 1775).
connect_air(cochin, ranchi, 1775).
connect_air(ranchi, delhi, 1000).
connect_air(delhi, ranchi, 1000).
connect_air(ranchi, hyderabad, 973).
connect_air(hyderabad, ranchi, 973).
connect_air(ranchi, indore, 971).
connect_air(indore, ranchi, 971).
connect_air(ranchi, jaipur, 1039).
connect_air(jaipur, ranchi, 1039).
connect_air(ranchi, kanpur, 610).
connect_air(kanpur, ranchi, 610).
connect_air(ranchi, lucknow, 588).
connect_air(lucknow, ranchi, 588).
connect_air(ranchi, madras, 1264).
connect_air(madras, ranchi, 1264).
connect_air(ranchi, nagpur, 686).
connect_air(nagpur, ranchi, 686).
connect_air(ranchi, nasik, 1248).
connect_air(nasik, ranchi, 1248).
connect_air(ranchi, panjim, 1488).
connect_air(panjim, ranchi, 1488).
connect_air(ranchi, patna, 253).
connect_air(patna, ranchi, 253).
connect_air(ranchi, pondicherry, 1399).
connect_air(pondicherry, ranchi, 1399).
connect_air(ranchi, pune, 1306).
connect_air(pune, ranchi, 1306).
connect_air(shillong, ahmedabad, 1980).
connect_air(ahmedabad, shillong, 1980).
connect_air(shillong, bangalore, 2053).
connect_air(bangalore, shillong, 2053).
connect_air(shillong, bhubaneshwar, 856).
connect_air(bhubaneshwar, shillong, 856).
connect_air(shillong, bombay, 2086).
connect_air(bombay, shillong, 2086).
connect_air(shillong, calcutta, 491).
connect_air(calcutta, shillong, 491).
connect_air(shillong, chandigarh, 1589).
connect_air(chandigarh, shillong, 1589).
connect_air(shillong, cochin, 2398).
connect_air(cochin, shillong, 2398).
connect_air(shillong, delhi, 1492).
connect_air(delhi, shillong, 1492).
connect_air(shillong, hyderabad, 1660).
connect_air(hyderabad, shillong, 1660).
connect_air(shillong, indore, 1659).
connect_air(indore, shillong, 1659).
connect_air(shillong, jaipur, 1614).
connect_air(jaipur, shillong, 1614).
connect_air(shillong, kanpur, 1161).
connect_air(kanpur, shillong, 1161).
connect_air(shillong, lucknow, 1102).
connect_air(lucknow, shillong, 1102).
connect_air(shillong, madras, 1852).
connect_air(madras, shillong, 1852).
connect_air(shillong, nagpur, 1398).
connect_air(nagpur, shillong, 1398).
connect_air(shillong, nasik, 1957).
connect_air(nasik, shillong, 1957).
connect_air(shillong, panjim, 2189).
connect_air(panjim, shillong, 2189).
connect_air(shillong, patna, 678).
connect_air(patna, shillong, 678).
connect_air(shillong, pondicherry, 1982).
connect_air(pondicherry, shillong, 1982).
connect_air(shillong, pune, 2018).
connect_air(pune, shillong, 2018).
connect_air(shimla, ahmedabad, 1007).
connect_air(ahmedabad, shimla, 1007).
connect_air(shimla, bangalore, 2019).
connect_air(bangalore, shimla, 2019).
connect_air(shimla, bhubaneshwar, 1483).
connect_air(bhubaneshwar, shimla, 1483).
connect_air(shimla, bombay, 1407).
connect_air(bombay, shimla, 1407).
connect_air(shimla, calcutta, 1461).
connect_air(calcutta, shimla, 1461).
connect_air(shimla, chandigarh, 55).
connect_air(chandigarh, shimla, 55).
connect_air(shimla, cochin, 2357).
connect_air(cochin, shimla, 2357).
connect_air(shimla, delhi, 275).
connect_air(delhi, shimla, 275).
connect_air(shimla, hyderabad, 1533).
connect_air(hyderabad, shimla, 1533).
connect_air(shimla, indore, 942).
connect_air(indore, shimla, 942).
connect_air(shimla, jaipur, 486).
connect_air(jaipur, shimla, 486).
connect_air(shimla, kanpur, 603).
connect_air(kanpur, shimla, 603).
connect_air(shimla, lucknow, 600).
connect_air(lucknow, shimla, 600).
connect_air(shimla, madras, 2034).
connect_air(madras, shimla, 2034).
connect_air(shimla, nagpur, 1125).
connect_air(nagpur, shimla, 1125).
connect_air(shimla, nasik, 1282).
connect_air(nasik, shimla, 1282).
connect_air(shimla, panjim, 1771).
connect_air(panjim, shimla, 1771).
connect_air(shimla, patna, 992).
connect_air(patna, shimla, 992).
connect_air(shimla, pondicherry, 2152).
connect_air(pondicherry, shimla, 2152).
connect_air(shimla, pune, 1440).
connect_air(pune, shimla, 1440).
connect_air(surat, ahmedabad, 207).
connect_air(ahmedabad, surat, 207).
connect_air(surat, bangalore, 1047).
connect_air(bangalore, surat, 1047).
connect_air(surat, bhubaneshwar, 1358).
connect_air(bhubaneshwar, surat, 1358).
connect_air(surat, bombay, 236).
connect_air(bombay, surat, 236).
connect_air(surat, calcutta, 1613).
connect_air(calcutta, surat, 1613).
connect_air(surat, chandigarh, 1133).
connect_air(chandigarh, surat, 1133).
connect_air(surat, cochin, 1305).
connect_air(cochin, surat, 1305).
connect_air(surat, delhi, 940).
connect_air(delhi, surat, 940).
connect_air(surat, hyderabad, 731).
connect_air(hyderabad, surat, 731).
connect_air(surat, indore, 357).
connect_air(indore, surat, 357).
connect_air(surat, jaipur, 704).
connect_air(jaipur, surat, 704).
connect_air(surat, kanpur, 963).
connect_air(kanpur, surat, 963).
connect_air(surat, lucknow, 1038).
connect_air(lucknow, surat, 1038).
connect_air(surat, madras, 1202).
connect_air(madras, surat, 1202).
connect_air(surat, nagpur, 651).
connect_air(nagpur, surat, 651).
connect_air(surat, nasik, 167).
connect_air(nasik, surat, 167).
connect_air(surat, panjim, 643).
connect_air(panjim, surat, 643).
connect_air(surat, patna, 1351).
connect_air(patna, surat, 1351).
connect_air(surat, pondicherry, 1271).
connect_air(pondicherry, surat, 1271).
connect_air(surat, pune, 317).
connect_air(pune, surat, 317).
connect_air(trivandrum, ahmedabad, 1687).
connect_air(ahmedabad, trivandrum, 1687).
connect_air(trivandrum, bangalore, 504).
connect_air(bangalore, trivandrum, 504).
connect_air(trivandrum, bhubaneshwar, 1625).
connect_air(bhubaneshwar, trivandrum, 1625).
connect_air(trivandrum, bombay, 1258).
connect_air(bombay, trivandrum, 1258).
connect_air(trivandrum, calcutta, 1987).
connect_air(calcutta, trivandrum, 1987).
connect_air(trivandrum, chandigarh, 2477).
connect_air(chandigarh, trivandrum, 2477).
connect_air(trivandrum, cochin, 180).
connect_air(cochin, trivandrum, 180).
connect_air(trivandrum, delhi, 2244).
connect_air(delhi, trivandrum, 2244).
connect_air(trivandrum, hyderabad, 1005).
connect_air(hyderabad, trivandrum, 1005).
connect_air(trivandrum, indore, 1589).
connect_air(indore, trivandrum, 1589).
connect_air(trivandrum, jaipur, 2055).
connect_air(jaipur, trivandrum, 2055).
connect_air(trivandrum, kanpur, 2032).
connect_air(kanpur, trivandrum, 2032).
connect_air(trivandrum, lucknow, 2087).
connect_air(lucknow, trivandrum, 2087).
connect_air(trivandrum, madras, 624).
connect_air(madras, trivandrum, 624).
connect_air(trivandrum, nagpur, 1428).
connect_air(nagpur, trivandrum, 1428).
connect_air(trivandrum, nasik, 1326).
connect_air(nasik, trivandrum, 1326).
connect_air(trivandrum, panjim, 851).
connect_air(panjim, trivandrum, 851).
connect_air(trivandrum, patna, 2095).
connect_air(patna, trivandrum, 2095).
connect_air(trivandrum, pondicherry, 494).
connect_air(pondicherry, trivandrum, 494).
connect_air(trivandrum, pune, 1166).
connect_air(pune, trivandrum, 1166).
connect_air(varanasi, ahmedabad, 1087).
connect_air(ahmedabad, varanasi, 1087).
connect_air(varanasi, bangalore, 1486).
connect_air(bangalore, varanasi, 1486).
connect_air(varanasi, bhubaneshwar, 631).
connect_air(bhubaneshwar, varanasi, 631).
connect_air(varanasi, bombay, 1251).
connect_air(bombay, varanasi, 1251).
connect_air(varanasi, calcutta, 628).
connect_air(calcutta, varanasi, 628).
connect_air(varanasi, chandigarh, 857).
connect_air(chandigarh, varanasi, 857).
connect_air(varanasi, cochin, 1852).
connect_air(cochin, varanasi, 1852).
connect_air(varanasi, delhi, 680).
connect_air(delhi, varanasi, 680).
connect_air(varanasi, hyderabad, 998).
connect_air(hyderabad, varanasi, 998).
connect_air(varanasi, indore, 779).
connect_air(indore, varanasi, 779).
connect_air(varanasi, jaipur, 740).
connect_air(jaipur, varanasi, 740).
connect_air(varanasi, kanpur, 293).
connect_air(kanpur, varanasi, 293).
connect_air(varanasi, lucknow, 265).
connect_air(lucknow, varanasi, 265).
connect_air(varanasi, madras, 1394).
connect_air(madras, varanasi, 1394).
connect_air(varanasi, nagpur, 611).
connect_air(nagpur, varanasi, 611).
connect_air(varanasi, nasik, 1114).
connect_air(nasik, varanasi, 1114).
connect_air(varanasi, panjim, 1451).
connect_air(panjim, varanasi, 1451).
connect_air(varanasi, patna, 220).
connect_air(patna, varanasi, 220).
connect_air(varanasi, pondicherry, 1528).
connect_air(pondicherry, varanasi, 1528).
connect_air(varanasi, pune, 1208).
connect_air(pune, varanasi, 1208).
connect_air(vijayawada, ahmedabad, 1116).
connect_air(ahmedabad, vijayawada, 1116).
connect_air(vijayawada, bangalore, 513).
connect_air(bangalore, vijayawada, 513).
connect_air(vijayawada, bhubaneshwar, 691).
connect_air(bhubaneshwar, vijayawada, 691).
connect_air(vijayawada, bombay, 872).
connect_air(bombay, vijayawada, 872).
connect_air(vijayawada, calcutta, 1054).
connect_air(calcutta, vijayawada, 1054).
connect_air(vijayawada, chandigarh, 1632).
connect_air(chandigarh, vijayawada, 1632).
connect_air(vijayawada, cochin, 871).
connect_air(cochin, vijayawada, 871).
connect_air(vijayawada, delhi, 1395).
connect_air(delhi, vijayawada, 1395).
connect_air(vijayawada, hyderabad, 250).
connect_air(hyderabad, vijayawada, 250).
connect_air(vijayawada, indore, 855).
connect_air(indore, vijayawada, 855).
connect_air(vijayawada, jaipur, 1263).
connect_air(jaipur, vijayawada, 1263).
connect_air(vijayawada, kanpur, 1108).
connect_air(kanpur, vijayawada, 1108).
connect_air(vijayawada, lucknow, 1152).
connect_air(lucknow, vijayawada, 1152).
connect_air(vijayawada, madras, 386).
connect_air(madras, vijayawada, 386).
connect_air(vijayawada, nagpur, 542).
connect_air(nagpur, vijayawada, 542).
connect_air(vijayawada, nasik, 823).
connect_air(nasik, vijayawada, 823).
connect_air(vijayawada, panjim, 739).
connect_air(panjim, vijayawada, 739).
connect_air(vijayawada, patna, 1116).
connect_air(patna, vijayawada, 1116).
connect_air(vijayawada, pondicherry, 518).
connect_air(pondicherry, vijayawada, 518).
connect_air(vijayawada, pune, 755).
connect_air(pune, vijayawada, 755).
connect_air(vishakapatnam, ahmedabad, 1261).
connect_air(ahmedabad, vishakapatnam, 1261).
connect_air(vishakapatnam, bangalore, 800).
connect_air(bangalore, vishakapatnam, 800).
connect_air(vishakapatnam, bhubaneshwar, 400).
connect_air(bhubaneshwar, vishakapatnam, 400).
connect_air(vishakapatnam, bombay, 1103).
connect_air(bombay, vishakapatnam, 1103).
connect_air(vishakapatnam, calcutta, 765).
connect_air(calcutta, vishakapatnam, 765).
connect_air(vishakapatnam, chandigarh, 1592).
connect_air(chandigarh, vishakapatnam, 1592).
connect_air(vishakapatnam, cochin, 1143).
connect_air(cochin, vishakapatnam, 1143).
connect_air(vishakapatnam, delhi, 1364).
connect_air(delhi, vishakapatnam, 1364).
connect_air(vishakapatnam, hyderabad, 504).
connect_air(hyderabad, vishakapatnam, 504).
connect_air(vishakapatnam, indore, 951).
connect_air(indore, vishakapatnam, 951).
connect_air(vishakapatnam, jaipur, 1280).
connect_air(jaipur, vishakapatnam, 1280).
connect_air(vishakapatnam, kanpur, 1020).
connect_air(kanpur, vishakapatnam, 1020).
connect_air(vishakapatnam, lucknow, 1046).
connect_air(lucknow, vishakapatnam, 1046).
connect_air(vishakapatnam, madras, 606).
connect_air(madras, vishakapatnam, 606).
connect_air(vishakapatnam, nagpur, 580).
connect_air(nagpur, vishakapatnam, 580).
connect_air(vishakapatnam, nasik, 1026).
connect_air(nasik, vishakapatnam, 1026).
connect_air(vishakapatnam, panjim, 1032).
connect_air(panjim, vishakapatnam, 1032).
connect_air(vishakapatnam, patna, 904).
connect_air(patna, vishakapatnam, 904).
connect_air(vishakapatnam, pondicherry, 740).
connect_air(pondicherry, vishakapatnam, 740).
connect_air(vishakapatnam, pune, 995).
connect_air(pune, vishakapatnam, 995).
connect_air(Ahmedabad, Ahmedabad, 0).
connect_air(Bangalore, Bangalore, 0).
connect_air(Bhubaneshwar, Bhubaneshwar, 0).
connect_air(Bombay, Bombay, 0).
connect_air(Calcutta, Calcutta, 0).
connect_air(Chandigarh, Chandigarh, 0).
connect_air(Cochin, Cochin, 0).
connect_air(Delhi, Delhi, 0).
connect_air(Hyderabad, Hyderabad, 0).
connect_air(Indore, Indore, 0).
connect_air(Jaipur, Jaipur, 0).
connect_air(Kanpur, Kanpur, 0).
connect_air(Lucknow, Lucknow, 0).
connect_air(Madras, Madras, 0).
connect_air(Nagpur, Nagpur, 0).
connect_air(Nasik, Nasik, 0).
connect_air(Panjim, Panjim, 0).
connect_air(Patna, Patna, 0).
connect_air(Pondicherry, Pondicherry, 0).
connect_air(Pune, Pune, 0).
connect_air(agartala, agartala, 0).
connect_air(agra, agra, 0).
connect_air(ahmedabad, ahmedabad, 0).
connect_air(allahabad, allahabad, 0).
connect_air(amritsar, amritsar, 0).
connect_air(asansol, asansol, 0).
connect_air(bangalore, bangalore, 0).
connect_air(baroda, baroda, 0).
connect_air(bhopal, bhopal, 0).
connect_air(bhubaneshwar, bhubaneshwar, 0).
connect_air(bombay, bombay, 0).
connect_air(calcutta, calcutta, 0).
connect_air(calicut, calicut, 0).
connect_air(chandigarh, chandigarh, 0).
connect_air(cochin, cochin, 0).
connect_air(coimbatore, coimbatore, 0).
connect_air(delhi, delhi, 0).
connect_air(gwalior, gwalior, 0).
connect_air(hubli, hubli, 0).
connect_air(hyderabad, hyderabad, 0).
connect_air(imphal, imphal, 0).
connect_air(indore, indore, 0).
connect_air(jabalpur, jabalpur, 0).
connect_air(jaipur, jaipur, 0).
connect_air(jamshedpur, jamshedpur, 0).
connect_air(jullundur, jullundur, 0).
connect_air(kanpur, kanpur, 0).
connect_air(kolhapur, kolhapur, 0).
connect_air(lucknow, lucknow, 0).
connect_air(ludhiana, ludhiana, 0).
connect_air(madras, madras, 0).
connect_air(madurai, madurai, 0).
connect_air(meerut, meerut, 0).
connect_air(nagpur, nagpur, 0).
connect_air(nasik, nasik, 0).
connect_air(panjim, panjim, 0).
connect_air(patna, patna, 0).
connect_air(pondicherry, pondicherry, 0).
connect_air(pune, pune, 0).
connect_air(ranchi, ranchi, 0).
connect_air(shillong, shillong, 0).
connect_air(shimla, shimla, 0).
connect_air(surat, surat, 0).
connect_air(trivandrum, trivandrum, 0).
connect_air(varanasi, varanasi, 0).
connect_air(vijayawada, vijayawada, 0).
connect_air(vishakapatnam, vishakapatnam, 0).
